import { ArrowRight, Sparkles, TrendingUp, Radio } from 'lucide-react'

const features = [
  {
    icon: Sparkles,
    color: 'text-cyan-400 bg-cyan-500/10',
    title: 'AI-Powered Analysis',
    desc: 'Real-time anomaly detection and campaign insights generated by Gemini.',
  },
  {
    icon: TrendingUp,
    color: 'text-emerald-400 bg-emerald-500/10',
    title: 'Trend Intelligence',
    desc: 'Cross-platform performance trends across impressions, conversions, and revenue.',
  },
  {
    icon: Radio,
    color: 'text-indigo-400 bg-indigo-500/10',
    title: 'Live Monitoring',
    desc: 'Instant ingestion with automatic anomaly detection the moment data lands.',
  },
]

export default function Splash({ onDone }) {
  return (
    <div className="min-h-screen flex items-center justify-center bg-[#0B0F17] relative overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(34,211,238,0.08),transparent_60%)]" />

      <div className="relative bg-[#111726] border border-slate-800 rounded-2xl p-10 w-full max-w-lg">
        <div className="flex flex-col items-center text-center mb-6">
          <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-cyan-400 to-blue-600 flex items-center justify-center font-bold text-slate-900 text-2xl mb-4">
            M
          </div>
          <p className="text-slate-400 text-xs tracking-[0.3em] uppercase mb-1">Welcome to</p>
          <h1
            className="text-4xl font-bold text-white tracking-tight"
            style={{ fontFamily: 'Space Grotesk, sans-serif' }}
          >
            MERCORA
          </h1>
          <p className="text-slate-400 text-sm mt-4 max-w-sm">
            Your campaign intelligence platform — ingesting data across every channel and turning it into clear, actionable analysis.
          </p>
        </div>

        <div className="space-y-3 mb-8">
          {features.map(({ icon: Icon, color, title, desc }) => (
            <div key={title} className="flex items-start gap-3 bg-[#0B0F17] border border-slate-800 rounded-lg p-3">
              <div className={`w-8 h-8 rounded-md flex items-center justify-center shrink-0 ${color}`}>
                <Icon size={16} />
              </div>
              <div>
                <p className="text-white text-sm font-medium">{title}</p>
                <p className="text-slate-500 text-xs mt-0.5">{desc}</p>
              </div>
            </div>
          ))}
        </div>

         <div className="flex items-center justify-between">
          <p className="text-slate-600 text-xs">v1.0.0 · Q3 2026</p>
          <button
            onClick={onDone}
            className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-cyan-400 to-blue-500 text-slate-900 text-sm font-semibold rounded-lg hover:opacity-90 transition-opacity"
          >
            Enter Dashboard
            <ArrowRight size={15} />
          </button>
        </div>
      </div>
    </div>
  )
}